### ISSUE TITLE
Errors during "npm install"

### ISSUE THREAD

**Issue by joshstrange** [goinstant/goangular#4] opened 2013-10-23 01:25 UTC
[Here](http://pastebin.com/w6SXMbGX) is a pastebin of the output from `npm install`

I am able to run `grunt build` and it will report `Done, without errors.` however it seems to throw an error during `grunt build` : 

```
Loading "saucelabs.js" tasks...ERROR
>> Error: Cannot find module 'request'

Running "clean:0" (clean) task

Running "clean:1" (clean) task
Cleaning dist...OK

Running "clean:2" (clean) task

Running "component:install" task
component install - start
component install - done

Running "component:build:dev" task

Done, without errors.
```

I am also able to run the mocha test and they all passed but it is throwing a 404 on `file://localhost/Users/.../goangular/build/build.css` I see the build.js file but no build.css in the build folder. I'm not sure if that is expected. I will report back if I run into any issues but at this time I'm not seeing any problems arising from the earlier warnings/errors. I just wanted to report them so that they could be cleaned up as to not confuse anyone else.

**Comment by lgtml** [comment] 2013-10-23 02:36
Have you tried running `npm install` again?

**Comment by lgtml** [comment] 2013-10-23 12:13
Hey Josh,
  I did not receive this error(with v0.10.11) but after a little research I found indications that this is a problem with npm + node < v0.10.19, we will look into this further this morning. You may want to try upgrading to the latest node and trying:

```
npm cache clear
npm install
```

Here is a link to the npm issue for your reference [here](https://github.com/isaacs/npm/issues/2907)

Let us know if you run in to any other issues or this one remains.

@mattcreager @nealstewart

Thank you,
Leigh

**Comment by nealstewart** [comment] 2013-10-23 13:13
There shouldn't be a `build.css` linked in that file. That's just a mistake. Thanks, @joshstrange!

**Comment by nealstewart** [comment] 2013-10-23 13:15
As @lgtml mentioned, the other error sounds like an npm failure.

**Comment by joshstrange** [comment] 2013-10-23 14:11
@lgtml I am running node v0.10.0 so it looks like I do need to update. I will update an try again. Also if I re-run `npm install` I always get:

```
npm WARN excluding symbolic link static/index.js -> ../index.js
npm WARN excluding symbolic link static/lodash.js -> ../node_modules/lodash/lodash.js
npm WARN excluding symbolic link static/mocha.css -> ../node_modules/mocha/mocha.css
npm WARN excluding symbolic link static/mocha.js -> ../node_modules/mocha/mocha.js
npm WARN excluding symbolic link static/test.js -> ../test/test.js
```

However you can probably disregard this as it's probably due to my node version as you pointed out.

**Comment by lgtml** [comment] 2013-10-23 14:28
The above errors are normally caused by cache issues, after you upgrade and clean cache they should disappear.

Take care and keep us posted.

**Comment by joshstrange** [comment] 2013-10-23 14:30
Ok, I just updated node to v0.10.21 and I am not getting any errors on `npm install` I still get those warn's that I mentioned above but like I said, they don't seem to be affecting anything.

Pastebin dump [here](http://pastebin.com/Jaf5MnGz)

**Comment by lgtml** [comment] 2013-10-23 15:21
Glad everything is working for you! Did these warnings till come up after a `npm cache clear`?

**Comment by joshstrange** [comment] 2013-10-23 15:23
I just ran `npm cache clear` and it doesn't seem to be making a difference:

```
>>> npm cache clear
>>> npm install
npm WARN excluding symbolic link static/index.js -> ../index.js
npm WARN excluding symbolic link static/lodash.js -> ../node_modules/lodash/lodash.js
npm WARN excluding symbolic link static/mocha.css -> ../node_modules/mocha/mocha.css
npm WARN excluding symbolic link static/mocha.js -> ../node_modules/mocha/mocha.js
npm WARN excluding symbolic link static/test.js -> ../test/test.js
```

**Comment by lgtml** [comment] 2013-10-23 18:25
Hey @joshstrange not sure why the warnings have not disappeared but it does not seem to affecting your use of NPM or goangular.

I am going to close this issue for now, let us know if you run into anything else.

**Closed as completed by lgtml** 2013-10-23 18:25 UTC

**Comment by joshstrange** [comment] 2013-10-23 19:10
@lgtml Thanks! I should have closed it with my last comment as like you said everything is working.
